---
title: "Pilot analysis"
author: "Carolyn Au"
date: "February 22, 2016"
output: html_document
---


```{r, echo=FALSE}
rm(list=ls())
library(tidyr)
library(dplyr)
library(rjson)
library(langcog) # devtools::install_github("langcog/langcog")
```

# Data prep

```{r}
path <- "~/code/aucProject/data/"
files <- dir(paste0(path,"sandbox-results/"), pattern = "*.json")
d.raw <- data.frame()

for (f in files) {
  jf <- paste0(path, "sandbox-results/", f)
  jd <- fromJSON(paste(readLines(jf), collapse=""))
  id <- data.frame(workerid = jd$workerId,
                   face_dft = jd$data$face, 
                   face_rating = jd$data$rating,
                   exp_type = jd$data$type,
                   elapsed_ms = jd$data$elapsed_ms,
                   num_errors = jd$data$num_errors,
                   gender = jd$data$gender,
                   education = jd$data$education)
                   #race = jd$data$race)
  d.raw <- bind_rows(d.raw, id)
}

# Number of participants
length(unique(d.raw$workerid))
```

```{r}
ggplot(d.raw, aes(x=face_dft, y=face_rating, color=factor(workerid))) +
  geom_point(stat="identity", alpha=0.5) + 
  facet_wrap(~workerid)
```